### ISSUE TITLE
 peer-to-peer code reviews

### ISSUE THREAD

**Issue by zemola** [Mithi-code/Resume-task#1]
Hello @Mithi-code 👍 😃 

### Review of your Resume Project

Great job, you must have put in some hard work, you are close but there are some changes you need to make.

1.  Use semantic HTML tags
2. Create a separate CSS file
3. Use a proper class name for code readability

Cheers, Happy coding!!!

**Comment by Mithi-code** [comment]
Thanks for your feedback
Closed #1
